### ISSUE TITLE
Pre-release testing of Mopidy.js v1.0

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy.js#17]
The release of Mopidy.js 1.0 is getting nearer. Due to the amount of changes in Mopidy.js since v0.5, I'd like to get some pre-release testing by existing Mopidy web clients before pushing a release to npm.

To build a single JS file to test with:
1. clone the mopidy.js git repo,
2. run `yarn` to install dependencies and then
3. run `yarn build` to build `dist/mopidy.js`.

All breaking changes are documented in the [changelog](https://github.com/mopidy/mopidy.js/blob/master/CHANGELOG.md).

@tkem Do you have time to try Mopidy.js' master branch with Mopidy-Mobile?

@kingosticks @jcass77 Does any of you have time to try Mopidy.js' master branch with Mopidy-Musicbox-Webclient?

@jaedb Do you have time to try Mopidy.js' master branch with Mopidy-Iris?

**Comment by tkem** [comment]
@jodal: I'll try to find some this week. Please poke me again if you haven't heard from me by Friday...

**Comment by tkem** [comment]
Well, whatever that `mopidy.js` does that's created by `yarn build`, it doesn't define something called Mopidy`, at least for me...

Test code:
```
<script src="dist/mopidy.js"></script>
<script>
  console.log(Mopidy);
</script>
```
`ReferenceError: Mopidy is not defined`

**Comment by jodal** [comment]
Thanks for the heads up! 70da720e720805ccc8f96346a0e5c2ed20d01bd4 should fix this.

**Comment by tkem** [comment]
@jodal: Looks much better now ;-)
Will try to test at least basic functionality with MoMo over the next couple of days...

**Comment by tkem** [comment]
@jodal: One more thing - even after changing function signatures, I get 
```
Error: mopidy.off is not a function
```
Apparently `mopidy.on()` and `mopidy.once()` are defined, but `mopidy.off()` isn't:
```
> mopidy.on
function addListener()
> mopidy.once
function once()
> mopidy.off
undefined
```

**Comment by tkem** [comment]
Sorry, should have read the changelog more carefully... `mopidy.removeListener()` is there, as is `mopidy.removeAllListeners()`, which should replace `mopidy.off()` without arguments.

**Comment by jodal** [comment]
I believe that `mopidy.off(event, listener)` will work with the GitHub release page download, as long as I build Mopidy.js on Node.js >= 10, since the event library is lifted directly from Node.js. We could smoothen that out a bit, and make us a bit more independent of the Node.js version, by explicitly defining `.off(event, listener)` on the `Mopidy` class and forward the call to `.removeListener()`. That said, `.removeListener()` and `.removeAllListeners()` have been in the Node.js event API since forever, so they are a sure bet either way.

The second calling convention, which now is the only one, was added in Mopidy 0.19.0 (ref https://github.com/mopidy/mopidy/blob/develop/docs/changelog.rst#v0190-2014-07-21). I don't remember if anything was changed on the server side back then, or if that was just a client side addition to Mopidy.js. Anyway, Mopidy.js should at least work with Mopidy 0.19 and newer, and maybe earlier versions too, depending on the support for the calling convention.

**Comment by jodal** [comment]
I forgot about Bower...

I assume we could add a `bower.json` and register it at bower.io.

However, it looks like the bower.io web site recommends migrating to other tools, and with Mopidy.js 1.0 being around 12 kB (down from 30 kB in 0.5), I assume you can continue bundling it until MoMo gets the modernization treatment I've just given Mopidy.js? :-)

**Comment by tkem** [comment]
I guess I'll find some way regarding the Bower issue, but even though MoMo v2.0 has been on my list for quite a while, it won't happen before 2019, I'm afraid ;-)

**Comment by jodal** [comment]
I've cleaned up and updated the Mopidy.js docs from the `mopidy` repo and moved them to the [README in this repo](https://github.com/mopidy/mopidy.js#mopidyjs). Please have a read through of that as well.

As for the changes related to `.off()` usage, I've reimplemented most ways of using `.off()` in PR #18. Please see if that makes the migration easier for you.

**Comment by tkem** [comment]
Didn't test the functionality yet, but I think reimplementing `.off()` as in PR #18 and removing any references to Node.js and `removeListener` will indeed make migration simpler and the changelog less confusing :+1:

**Comment by kingosticks** [comment]
I think I've made the necessary changes to Mopidy-Musicbox-Webclient (and websettings). It wasn't totally obvious to me at first why there was no longer a .min file and instead this .map file but I guess it's obvious if you know more than 5 minutes of javascript.  Should that be added to the changelog?

**Comment by jodal** [comment]
@tkem Like you suggested, I merged #18 and removed all references to Node.js and `removeListener`.

@kingosticks I added a note about the change in prebuilt files to the top of the changelog.

All of you, thanks for your testing! Mopidy.js v1.0.0 is now available from npm. First release in almost four years :tada:

**Comment by kingosticks** [comment]
Woo! Nice one.
